trigger:
- main

pool: AzureWorkflowTutorial

steps:
- task: Bash@3
  displayName: Prints repository name
  inputs:
    targetType: 'inline'
    script: |
      REPOSITORY_NAME="$(cut -d'/' -f2 <<< $(Build.Repository.Name))"
      echo "$REPOSITORY_NAME"
      echo "$(pwd)"
- task: Bash@3
  displayName: Checks for python version
  inputs:
    targetType: 'inline'
    script: |
      echo "$REPOSITORY_NAME"
      pip --version
      pip install black
      ls -la