trigger:
- main
- release/*
- development

pr:
- development

pool: AzureWorkflowTutorial

variables:
  isFeature: $[eq(variables['System.PullRequest.SourceBranch'], 'feature/')]
  isRelease: $[eq(variables['Build.SourceBranch'], 'release/*')]
  isDevelopment: $[eq(variables['Build.SourceBranch'], 'development')]
  isMain: $[eq(variables['Build.SourceBranch'], 'main')]
  global_variable: global_value    # this is available to all jobs

stages:
- stage:
  condition: eq(variables['Build.Reason'], 'PullRequest')
  displayName: Prepare
  - job:
    steps:
      - task: Bash@3
        displayName: Prepare variables
        inputs:
          targetType: 'inline'
          script: |
            set_variable(){
              echo "Set key $1 as $2"
              echo "##vso[task.setvariable variable=$1]$2"
            }
            echo $(GLOBAL_VARIABLE)
            if [[ "$(System.PullRequest.SourceBranch)" =~ .*"release/".* ]]; then
              echo "It's a release/* branch."
              set_variable "GLOBAL_VARIABLE" true
            fi
            echo $(GLOBAL_VARIABLE)
      - task: Bash@3
        displayName: Check variables
        inputs:
          targetType: 'inline'
          script: |
            echo $(GLOBAL_VARIABLE)