trigger:
- main
- release/*
- development

pr:
- development

pool: AzureWorkflowTutorial

stages:
- stage:
  displayName: Quality check
  jobs:
  - job:
    steps:
      - task: Bash@3
        displayName: Lint stage
        inputs:
          targetType: 'inline'
          script: |
            REPOSITORY_NAME="$(cut -d'/' -f2 <<< $(Build.Repository.Name))"
            echo "$REPOSITORY_NAME"
            echo "I'm the linting stage"
- stage:
  displayName: Automated tests
  jobs:
  - job:
    steps:
      - task: Bash@3
        displayName: Test stage
        inputs:
          targetType: 'inline'
          script: |
            echo "$REPOSITORY_NAME"
            echo "I'm the testing stage"
- stage:
  displayName: Build
  jobs:
  - job:
    steps:
      - task: Bash@3
        displayName: Build Stage
        inputs:
          targetType: 'inline'
          script: |
            echo "$REPOSITORY_NAME"
            echo "I'm the build stage"