trigger:
- main
- release/*
- development

pr:
- development

pool: AzureWorkflowTutorial

variables:
  isFeature: $[ contains('feature/', variables['System.PullRequest.SourceBranch']) ]
  isRelease: $[ contains('release/', variables['System.PullRequest.SourceBranch']) ]
  isDevelopment: $[eq(variables['Build.SourceBranch'], 'development')]
  isMain: $[eq(variables['Build.SourceBranch'], 'main')]

stages:
- stage:
  condition: eq(variables['Build.Reason'], 'PullRequest')
  displayName: Build
  variables:
    stage_variable: stage_variable
  jobs:
  - job:
    variables:
      job_variable: job_variable
    steps:
      - task: Bash@3
        displayName: Prepare
        inputs:
          targetType: 'inline'
          script: |
            echo "latest-qa"
            echo "$(Build.BuildId)-$(Build.SourceVersion)"
      - task: Bash@3
        displayName: Build Stage
        inputs:
          targetType: 'inline'
          script: |
            echo "Build reason is: $(Build.Reason)"
            echo "Build id is: $(Build.BuildId)"
            echo "Build source version is: $(Build.SourceVersion)"
            echo "Build source branch is: $(Build.SourceBranch)"
            echo "PR source branch: $(System.PullRequest.SourceBranch)"
            echo "PR target branch: $(System.PullRequest.TargetBranch)"
            echo "is feat?: $(isFeature)"
            echo "is release?: $(isRelease)"
            echo "is dev?: $(isDevelopment)"
            echo "is main?: $(isMain)"
            echo "I'm the build stage"
            # if current branch is develop or master or release/* make build