trigger:
- main

pool: AzureWorkflowTutorial

stages:
- stage:
  jobs:
  - job:
    steps:
      - task: Bash@3
        displayName: Get application name from repository
        inputs:
          targetType: 'inline'
          script: |
            REPOSITORY_NAME="$(cut -d'/' -f2 <<< $(Build.Repository.Name))"
            echo "$REPOSITORY_NAME"
            export REPOSITORY_NAME=$REPOSITORY_NAME
      - task: Bash@3
        displayName: Lint stage
        inputs:
          targetType: 'inline'
          script: |
            echo "$REPOSITORY_NAME"
            echo "I'm the linting stage"
- stage:
  jobs:
  - job:
    steps:
      - task: Bash@3
        displayName: Test stage
        inputs:
          targetType: 'inline'
          script: |
            echo "$REPOSITORY_NAME"
            echo "I'm the testing stage"
- stage:
  jobs:
  - job:
    steps:
      - task: Bash@3
        displayName: Build Stage
        inputs:
          targetType: 'inline'
          script: |
            echo "$REPOSITORY_NAME"
            echo "I'm the build stage"