trigger:
- main

pool: AzureWorkflowTutorial

steps:
- task: Bash@3
  displayName: Prints repository name
  inputs:
    targetType: 'inline'
    script: |
      REPOSITORY_NAME="$(cut -d'/' -f2 <<< $(Build.Repository.Name))"
      echo "$REPOSITORY_NAME"
      echo "$(pwd)"
- task: Bash@3
  displayName: Checks python3 version
  inputs:
    targetType: 'inline'
    script: |
      python3 --version
      pip3 install black
      black --check azure_workflow