trigger:
- main

pool: AzureWorkflowTutorial

steps:
- task: Bash@3
  displayName: Prints repository name
  inputs:
    targetType: 'inline'
    script: |
      REPOSITORY_NAME="$(cut -d'/' -f2 <<< $(Build.Repository.Name))"
      echo "$REPOSITORY_NAME"
      echo "$(pwd)"
- task: UsePythonVersion@0
  displayName: Adds latest python version
  inputs:
    versionSpec: '3.9.5'
    addToPath: true
    architecture: 'x64'
- task: Bash@3
  displayName: Checks for python version
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      python --version
      pip install black
      black --check azure_worflow