version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/dev.Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000

  tests:
    build:
      context: .
      dockerfile: ./dockerfiles/dev.Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app